services:
  client:
    build:
      context: ./Client
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    volumes:
      - ./Client:/app
      - /app/node_modules
    working_dir: /app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
    env_file:
      - .env.production
